# Generated by Django 5.0.6 on 2024-07-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recent_Event',
            new_name='RecentEvent',
        ),
    ]
