# Generated by Django 5.0.6 on 2024-07-07 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0002_rename_recent_event_recentevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentevent',
            old_name='event_picture',
            new_name='event_image',
        ),
        migrations.AddField(
            model_name='recentevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
